In [1]:
#Numpy
#linear Aljebra library (data science)

import numpy as np

In [2]:
#Creating numpy array for a list
my_list= [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
#built-in methods to generate arrays
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [7]:
#linspace (evenly spaced numbers over a speified interval)
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [8]:
#eye to create an I matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
#Create random arrays
np.random.rand(2)

array([0.73175548, 0.83058724])

In [10]:
np.random.rand(5,5)

array([[0.55731126, 0.13666757, 0.1381364 , 0.64815073, 0.00225874],
       [0.90440942, 0.14613867, 0.28507061, 0.29275585, 0.94588953],
       [0.67881598, 0.15306809, 0.73324255, 0.49316358, 0.86865762],
       [0.81436238, 0.49743199, 0.2642166 , 0.43702988, 0.05250665],
       [0.43002488, 0.19437448, 0.67872425, 0.61046509, 0.37643966]])

In [11]:
#Create random array from a standard normal distribution
np.random.randn(5,5)

array([[ 0.91713937,  0.54062512,  1.06317221, -1.25711589,  0.10881391],
       [ 0.59379257, -0.42576318,  1.20924305, -0.54029361,  0.30704985],
       [-0.22316904,  0.04975834, -0.69184807,  0.9304603 , -1.11941338],
       [ 1.24679168,  0.72849257,  0.56194567, -0.18091518,  1.42477183],
       [ 1.60433613, -1.54793371, -0.69102272, -0.14652415, -0.9415654 ]])

In [15]:
#Create random integer number
np.random.randint(1,100)
np.random.randint(1,100,10)

array([10,  8,  1, 34, 82, 70, 17, 13, 81, 78])

In [20]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
#inverse
from numpy.linalg import inv
a = np.random.randn(5,5)
b = inv(a)
d = np.matmul(a,b)
d

array([[ 1.00000000e+00,  2.08517238e-16,  5.21675536e-17,
        -2.11395014e-17, -8.22929419e-17],
       [ 1.34213567e-16,  1.00000000e+00, -2.10002242e-16,
         1.17486580e-16,  2.44614867e-16],
       [ 1.84982090e-16,  6.14564299e-17,  1.00000000e+00,
         3.89933606e-16, -5.81030147e-18],
       [ 2.70322418e-16, -1.27692486e-16,  2.15312624e-17,
         1.00000000e+00,  4.71447577e-17],
       [ 4.52204202e-18, -3.60120956e-17,  2.17503962e-17,
         2.69744478e-17,  1.00000000e+00]])